# Generated by Django 3.1 on 2020-08-05 21:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Address1', models.CharField(max_length=60)),
                ('Address2', models.CharField(max_length=60, null=True)),
                ('City', models.CharField(max_length=20)),
                ('State', models.CharField(max_length=2)),
                ('Zip', models.CharField(max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=255)),
                ('SelfReportedCashFlow', models.FloatField(max_length=255)),
                ('TaxID', models.CharField(max_length=255)),
                ('Phone', models.CharField(max_length=255)),
                ('NAICS', models.CharField(max_length=255)),
                ('HasBeenProfitable', models.BooleanField(max_length=255)),
                ('HasBankruptedInLast7Years', models.BooleanField(max_length=255)),
                ('InceptionDate', models.CharField(max_length=255)),
                ('Address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loanapp.address')),
            ],
        ),
    ]
